module.exports.BasicDataUser = class{
    name="";
    avatar="";
    id="";
    isVerifyEmail=false;
    numberNotReadNotifications=0;
    constructor(
        name="",
        avatar="",
        id="",
        isVerifyEmail=false,
        numberNotReadNotifications=0
    ){
        this.name=name;
        this.avatar=avatar;
        this.id=id;
        this.isVerifyEmail=isVerifyEmail;
        this.numberNotReadNotifications=numberNotReadNotifications;
    }
}
module.exports.RegisterReceiveEmailResponse = class{
    isVerifyEmail=false;
    addFriendRequest=false;
    teamRecruitRequest=false;
    teamJoinRequest=false;
    projectInviteRequest=false;
    constructor(
        isVerifyEmail=false,
        addFriendRequest=false,
        teamRecruitRequest=false,
        teamJoinRequest=false,
        projectInviteRequest=false,
    ){
        this.isVerifyEmail=isVerifyEmail;
        this.addFriendRequest=addFriendRequest;
        this.teamRecruitRequest=teamRecruitRequest;
        this.teamJoinRequest=teamJoinRequest;
        this.projectInviteRequest=projectInviteRequest;
    }
}